# Numpy

NumPy (Numerical Python) is an open source Python library that’s used for working with numerical data in Python. It is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

Numpy can also be used as an efficient multi-dimensional container of generic data.

# Installing Numpy
pip install numpy

# Importing Numpy
import numpy as np

# Numpy arrays
Creating a Basic Array

In [23]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np #importing numpy
arr1=np.array([1,2,3,4])#definig numpy in array
arr2=np.array(["a,b,c,d"])
arr3=np.array(["a",1,"b","c",2,"#"])
print(arr1)
print(arr2)
print(arr3)
print(type(arr1))
print(type(arr2))
print(type(arr3))

[1 2 3 4]
['a,b,c,d']
['a' '1' 'b' 'c' '2' '#']
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# #Arrays using np.zeros(), np.ones(), np.arange()

In [18]:
import numpy as np
zero=np.zeros(3)
print(zero)

[0. 0. 0.]


In [29]:
import numpy as np
one=np.ones(5)# numpy as ones to print for 5 times
a=np.arange(6)#numpy as to arange numbers up to 6
b=np.arange(1,20)#numpy as to arrange numbers from START argument-1 to End arugument-20
c=np.arange(1,30,5)#numpy as to arrnage start arugument-to End arugument-30 with a span of -Third argument 5
print(one)
print(a)
print(b)
print(c)
print(type(a))
print(type(b))
print(type(c))

[1. 1. 1. 1. 1.]
[0 1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  6 11 16 21 26]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# NdArray (N-Dimensional Array)
A 2-Dimensional Array

In [8]:
import numpy as np # importing numpy
array_1=np.array([[1,2,3],[4,5,6]])#2 Dimensional Array 2*array type
array_2=np.array([[1,2],[3,4],[5,6]])# 2 Dimensional with 3*3 array type
zero=np.zeros((3,3))#Creating zeros with 3*3 array
one=np.ones((4,4))# creating one  with 4*4 array
ones=np.ones((2,2),dtype='int64')  #specify the type with (dtype) parameter
print(array_1)
print(array_2)
print(zero)
print(one)
print(ones)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1]
 [1 1]]


# ndim____ndimensional
Cool Checkouts using this in print functional

In [11]:
import numpy as np
a=np.array(61)# index0
b=np.array([[61,106],[106,61]])#index 2
c=np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])#index2
d=np.array([[[1,2,3],[2,3,4],[3,4,5],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
2
2
3


Basic Operators in array

In [14]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=a+b
d=a-b
e=b/a
f=a*b
print(a)
print(b)
print("addition",c)
print("subtraction",d)
print("division",e)
print("multiplication",f)
print("adding 1 to alla elemnts",c+1)

[1 2 3 4]
[5 6 7 8]
addition [ 6  8 10 12]
subtraction [-4 -4 -4 -4]
division [5.         3.         2.33333333 2.        ]
multiplication [ 5 12 21 32]
adding 1 to alla elemnts [ 7  9 11 13]


array indexing & Slicing

In [27]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([[5,6],[7,8]])
c=np.array(['L','E','N','O','V','O'])
d=np.array([[[1,2],[2,3],[4,5]]])
print(a[0])#index 0
print(b[1])# whole index1
print(b[1,1])# in index 1, 1st element 
print(c[0:4])# Slicing similar to lists
print(d[0,0])
print(c[-1])
print(c[::-1])#reverse

1
[7 8]
8
['L' 'E' 'N' 'O']
[1 2]
O
['O' 'V' 'O' 'N' 'E' 'L']


# Numpy Functions

# Numpy array shape

In [30]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a.shape)# single set with 5 elements
print(b.shape)# two sets of 5 elemets of each

(5,)
(2, 5)


In [32]:
import numpy as np
a=np.array([[[0,1,2,3,4],
             [5,6,7,8,9]],
            [[0,1,2,3,4],
             [5,6,7,8,9]],
            [[0,1,2,3,4],
             [5,6,7,8,9]]])
print(a.ndim)#Gives Dimensions in array
print(a.shape)#gives set of elements
print(a.size)#gives number of elements

3
(3, 2, 5)
30


Reshaping 1 dimensional to 2 Dimensional

In [36]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr2=arr1.reshape(3,3)# Reshaping into 2 dimensional
arr3=np.array(['L','E','N','O','V','O'])
arr4=arr3.reshape(3,2)
print("reshape arr1",arr2)
print("reshape arr3",arr4)

reshape arr1 [[1 2 3]
 [4 5 6]
 [7 8 9]]
reshape arr3 [['L' 'E']
 ['N' 'O']
 ['V' 'O']]


Reshaping 1 dimensional to 3 dimensional

In [39]:
import numpy as np
a=np.arange(1,20)# getting elements from 1 to 20
b=a.reshape(2,5,2)#first argument(2)--2 elements in a set, second argument(5)--5 set of columns, third arguments(2) 
print("reshaping into multidimensional:",b)

reshaping into multidimensional: [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


reshaping multidimensional array into 1 dimensional

In [42]:
import numpy as np
a=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])
print(a.reshape(-1))# Reshaping

[1 2 3 4 5 6 7 8]


# Numpy sorting means according to ascending order

In [45]:
import numpy as np
a=np.array([8,5,6,7,2,3,4,8,9])# for numbers
print(np.sort(a))

[2 3 4 5 6 7 8 8 9]


In [47]:
import numpy as np
a=np.array(['a','g','h','r','i','k','s','n','i','a','g','j','b'])# sorting a str array
print(np.sort(a))

['a' 'a' 'b' 'g' 'g' 'h' 'i' 'i' 'j' 'k' 'n' 'r' 's']


In [53]:
import numpy as np
a=([[1,3,2],[8,3,2]])# sorting dimensional array
print(np.sort(a))

[[1 2 3]
 [2 3 8]]


# Numpy Searching
where:

In [55]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr1 == 4)# tells location of 4
y = np.where(arr1%2 == 0)
z = np.where(arr1%2 == 1)
print(x)
print(y)
print(z)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
(array([0, 2, 4], dtype=int64),)


searchsorted():

In [56]:
import numpy as np
arr1 = np.array([6, 7, 8, 9])
x = np.searchsorted(arr1, 7)
print(x)
   
   # Multiple values
arr2 = np.array([1, 3, 5, 7])
y = np.searchsorted(arr2, [2, 4, 6])
print(y)

1
[1 2 3]


# Mean, Median,Mode
Mean

In [58]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.mean(a))

5.5


Median

In [63]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array([1,4,5,6,7,28,9,20,34,77,44,65])
print(np.median(a))
print(np.median(b))

5.5
14.5


# Mode

In [66]:
from scipy import stats
a=([11,22,33,44,55,66,77,88,111])
print(stats.mode(a))

ModeResult(mode=array([11]), count=array([1]))


# Standard Deviation (σ)

In [67]:
import numpy as np
a=([11,22,33,44,55,66,77,88,111])
print(np.std(a))

30.630413353760378
