# Numpy
Numpy stands for numerical Python and is the code library for numerical and scientific operations
NumPy **(Numerical Python)** is an open source Python library that’s used  for working with numerical data in Python.
It is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

In [4]:
pip install numpy#numpy installation

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np# importing numpy

# single dimensional array

In [15]:
import numpy as np
n1=np.array([10,20,30,40])
arr1=np.array(['a','b','c','d'])
n2=np.array((10,'a',20,'b'))# for tuple
print(n1)
print(arr1)
print(n2)
print(type(n2))
print(type(n1))

[10 20 30 40]
['a' 'b' 'c' 'd']
['10' 'a' '20' 'b']
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# np.zeros(),np.ones(), np.arange()

In [21]:
# import numpy as np
a=np.zeros(10)
b=np.ones(5)
c=np.arange(10)
print(a)
print(b)
print(c)
print(type(a))
type(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


numpy.ndarray

# Array numpy with zeros((first argument,second argument))
np.zeros((1st argument,2nd argument))

In [24]:
import numpy as np
n1=np.zeros((2,3))# 2-rows and 3-columns
n2=np.zeros((5,5))# 5-rows and 5-columns
print(n1)
n2

[[0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Array with same number to be printed for the whole
#np.full((1,2),500)

In [25]:
_a=np.full((4,3),200)#printing 200 in 4-rows and 3-columns
_a


array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

# np.arange(first argument,second argument)

In [27]:
_b=np.arange(1,5)
_b

array([1, 2, 3, 4])

In [35]:
#np.arange(first argument,second argument,Third argument)
_c=np.arange(3,903,3)
print(_c)
print(len(_c))

[  3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51  54
  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105 108
 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162
 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216
 219 222 225 228 231 234 237 240 243 246 249 252 255 258 261 264 267 270
 273 276 279 282 285 288 291 294 297 300 303 306 309 312 315 318 321 324
 327 330 333 336 339 342 345 348 351 354 357 360 363 366 369 372 375 378
 381 384 387 390 393 396 399 402 405 408 411 414 417 420 423 426 429 432
 435 438 441 444 447 450 453 456 459 462 465 468 471 474 477 480 483 486
 489 492 495 498 501 504 507 510 513 516 519 522 525 528 531 534 537 540
 543 546 549 552 555 558 561 564 567 570 573 576 579 582 585 588 591 594
 597 600 603 606 609 612 615 618 621 624 627 630 633 636 639 642 645 648
 651 654 657 660 663 666 669 672 675 678 681 684 687 690 693 696 699 702
 705 708 711 714 717 720 723 726 729 732 735 738 74

# ramdom numbers

In [46]:
np.random.randint(101,505,5)

array([323, 130, 361, 171, 214])

# Array shape

In [51]:
n_1=np.array([[1,2,3,4],[5,6,7,8]])
print(n_1.shape)
n_1

(2, 4)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
n_1.shape=(4,2)
n_1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [104]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr1= np.array([1,2,3,4])
print(arr.shape)
print(arr1.shape)

(2, 4)
(4,)


In [105]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])
 
print('No of dimensions of the array:',array_example.ndim)     # .ndim for dimensions
print('Total no of elements of the array:',array_example.size) # .size for size
print('Shape of the array:',array_example.shape)                # .shape for shape

No of dimensions of the array: 3
Total no of elements of the array: 24
Shape of the array: (3, 2, 4)


In [106]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr1 = arr1.reshape(4, 3)
arr2 = np.array(['D','e','V','I','n','c','e','p','t'])
newarr2 = arr2.reshape(3,3)
print(newarr1)
print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[['D' 'e' 'V']
 ['I' 'n' 'c']
 ['e' 'p' 't']]


In [107]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [109]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## **NumPy Sorting and Searching**

### **NumPy Sorting**

In [111]:
   import numpy as np
   arr1 = np.array([3, 2, 0, 1])
   arr2 = np.array(['red','blue','green'])
   
   # 2-D array
   arr3 = np.array([[3, 2, 4], [5, 0, 1]])
   
   print(np.sort(arr1))
   print(np.sort(arr2))
   print(np.sort(arr3))

[0 1 2 3]
['blue' 'green' 'red']
[[2 3 4]
 [0 1 5]]


### **NumPy Searching**

**where() :**

In [112]:
   import numpy as np
   arr1 = np.array([1, 2, 3, 4, 5, 4, 4])
   x = np.where(arr1 == 4)
   y = np.where(arr1%2 == 0)
   z = np.where(arr1%2 == 1)
   print(x)
   print(y)
   print(z)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
(array([0, 2, 4], dtype=int64),)


**searchsorted() :**

In [113]:
   import numpy as np
   arr1 = np.array([6, 7, 8, 9])
   x = np.searchsorted(arr1, 7)
   print(x)
   
   # Multiple values
   arr2 = np.array([1, 3, 5, 7])
   y = np.searchsorted(arr2, [2, 4, 6])
   print(y)

1
[1 2 3]


### **Mean**

In [114]:
   import numpy
   # For one value in the middle
   speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]
   x = numpy.median(speed)
   print(x)
   
   # For two values in the middle
   speed1 = [99,86,87,88,86,103,87,94,78,77,85,86]
   y = numpy.median(speed1)
   print(y)

87.0
86.5


### **Mode**

In [116]:
   from scipy import stats
   speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]
   x = stats.mode(speed)
   print(x)

ModeResult(mode=array([86]), count=array([3]))


## **Standard Deviation (σ)**

In [117]:
   import numpy
   speed = [86,87,88,86,87,85,86]
   x = numpy.std(speed)
   print(x)
   
   speed1 = [32,111,138,28,59,77,97]
   y = numpy.std(speed1)
   print(y)

0.9035079029052513
37.84501153334721


# Stacking

In [55]:
#vstacking
na1=np.array([1,2,3])
na2=np.array([4,5,6])
np.vstack((na1,na2))

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
#hstack
np.hstack((na1,na2))

array([1, 2, 3, 4, 5, 6])

In [58]:
#column stack
np.column_stack((na1,na2))

array([[1, 4],
       [2, 5],
       [3, 6]])

# Numpy intersepection and Differance

In [61]:
n1=np.array([[1,2,3,4],[10,11,2,13]])
n2=np.array([[5,6,7,8],[10,11,12,3]])
np.intersect1d(n1,n2)#  To find the intersepection between the elements

array([ 3, 10, 11])

In [63]:
np.setdiff1d(n1,n2)

array([ 1,  2,  4, 13])

In [64]:
np.setdiff1d(n2,n1)

array([ 5,  6,  7,  8, 12])

# Array indexing slicing and basic operators are similar to Lists

In [72]:
n1=np.array([2,4,6])
n2=np.array([1,2,3])
print(n1+n2)
print(n1*n2)
print(n1-n2)
print(n1/n2)
print(n1+1)
print(n1*3)
print(n1*3)

[3 6 9]
[ 2  8 18]
[1 2 3]
[2. 2. 2.]
[3 5 7]
[ 6 12 18]
[ 6 12 18]


# Mutli dimensional array

In [20]:
import numpy as np
narray=np.array([[1,2,3,4],[5,6,7,8]])
print(narray)
type(narray)

[[1 2 3 4]
 [5 6 7 8]]


numpy.ndarray

# Slicing and Indexing

In [97]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
print(n1)
print(n1[1],[3])

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8] [3]


In [102]:
n1[0:1][1:2]

array([], shape=(0, 4), dtype=int32)